### ISSUE TITLE
False positive on non-number iterations

### ISSUE THREAD

**Issue by Marsup** [hapijs/rule-for-loop#2]
Hi,

I'm having a false-positive on this code :

``` js
const iter = set.values(); // this is a new Set()
for (let cur = iter.next(); !cur.done; cur = iter.next()) {
}
```

I don't really see the point of naming it `i`, it's not a number, any workaround to that ?

**Comment by cjihrig** [comment]
You could use the `eslint-disable-next-line` trick, use a different looping structure (this rule should only target old school `for` loops), abbreviate `iter` to `i` :trollface:.

I think making the rule actually recognize this pattern would probably turn out very hacky. I'd go with `eslint-disable-next-line` personally.

**Comment by Marsup** [comment]
I'd love to go for another loop but for-of is currently a deopt in V8 and a simple for is the only loop that allows you to call next consistently even with use of `continue`.

I think the only reliable way would be to check if a `next()` is called in the last part of the for.

I went with a disable on that line but I don't really like that.

**Comment by cjihrig** [comment]
I think even checking for `next()` could be problematic. Like if `next()` is aliased to something else, or there is some custom iterator that uses something not named `next()`, or if the last piece is a more complex expression. I think a line just has to be drawn somewhere. I'm going to close this as a V8 bug (sarcasm), because `for...of` shouldn't be a deopt :-)

**Comment by Marsup** [comment]
It's the spec... https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator
I agree it's tricky though...

**Comment by cjihrig** [comment]
I know `next()` is spec, but what I was getting at is that there is nothing stopping people from getting creative like `foo = next; foo();`. I want to avoid getting hacky trying to detect things.
